class parGroup:
    def __init__(self):
        self.clampMax: tuple
        self.clampMin: tuple
        self.default: tuple
        self.help: str
        self.isCustom: bool
        self.isFloat: bool
        self.isInt: bool
        self.isMomentary: bool
        self.isNumber: bool
        self.isOP: bool
        self.isPulse: bool
        self.isPython: bool
        self.isSequence: bool
        self.isString: bool
        self.isToggle: bool
        self.label: str
        self.max: tuple
        self.menuIndex: tuple
        self.menuLabels: tuple
        self.menuNames: tuple
        self.min: tuple
        self.name: str
        self.order: int
        self.style: str
        self.val: tuple
        self.index: int
        self.size: int
